### ISSUE TITLE
constant reconnects

### ISSUE THREAD

**Issue by Urbanshenkie** [kaaholst/android-squeezer#680] opened 2021-03-06 15:33 UTC
It's flinkering when it's connecting it's disconnect and then connect in a flikkering motion.

Same here the beta and earlier. I had it before 6 months ago. I'm thinking it's because android 10 and 11.  On 10 not that worst then on 11.

**Comment by xxxserxxx** [comment] 2021-03-09 16:39
I don't know about the reconnects, but a few weeks ago I started getting something like this; it completely took over my phone by causing the screen to flicker on and off, and to fix it I'd have to hold down the power button and hope I could hit the reboot option before the screen flickered again. I uninstalled and reinstalled, and it'd work for a couple of days and start doing it again.  Then it started happening on my wife's phone.  I keep re-installing it every week or two to see if it's stopped happening; 2.2.3 was released since the last time I tried, so I'm giving it another shot.

I'm connecting to LMS 8.0.0 on a Debian MintBox on a home LAN; there are two players always connected, squeezelite-pa on the same MintBox, and a Logitech Squeezebox controller (hardware).  The phones are both Pixel 2s running whatever the last build of Android 11 (same as @urbanshenkie) Google released for the phone.  The problems *may* have started after Android 11, but I can't be certain.

**Comment by Urbanshenkie** [comment] 2021-03-11 08:41
Try lowing your resolution of your phone. This helped me to fix the problem temporary.

**Comment by Dazrok2** [comment] 2021-03-26 06:36
Hello,
I'm having the same problem, on Android 10.

**Comment by Urbanshenkie** [comment] 2021-03-26 09:37
Dazrok2 clear the cache and data of the app it will temporarily fix the problem. I noticed that. It's a quick fix.

**Comment by kaaholst** [comment] 2021-03-30 06:09
For some reason Android or LMS looses the connection. I haven't been able to find any system in when or why. It may happen of course if there's an issue with the network, but for a few users it disconnects regularly. I am unable to reproduce this myself.

In an attempt to work around this issue I have made a new version of Squeezer which is available in beta. Squeezer attempts a rehandshake when the connection is lost. If that succeeds Squeezer will stay where it is. If that fails it will give up, to avoid an endless loop.

Opt in to receive beta versions of Squeezer by going to https://play.google.com/apps/testing/uk.org.ngo.squeezer and clicking the "Become a tester" button. You can opt out of the beta programme any time.

**Comment by Lurux** [comment] 2021-04-09 16:16
Hey,

Has the feature left out of beta yet ?

**Comment by kaaholst** [comment] 2021-04-09 21:21
No, not yet.
The reported issues of duplicated menu items, and that it doesn't update the current player state has to be fixed before it can be released.
I will upload a new beta version shortly, which hopefully will fix the issues.

**Comment by Lurux** [comment] 2021-04-10 18:03
Oh, ok, that makes sense.

I was asking on behalf of someone else, sorry I didn't look much into it !

**Comment by kaaholst** [comment] 2021-04-12 22:06
A new beta version is released which fixes the issues of issues of duplicated menu items, and resubscribe to the current player state.

**Comment by kaaholst** [comment] 2021-04-30 21:10
Version 2.2.4 with rehandshake on lost connection is released, so closing this

**Closed by kaaholst** 2021-04-30 21:10 UTC

**Comment by xxxserxxx** [comment] 2021-05-02 13:02
Belatedly confirming the beta stopped the hard take-over of my Android phone; my wife and I have been using it with no problems since the release.
