### ISSUE TITLE
Menu resets to top level after phone sleep

### ISSUE THREAD

**Issue by Frankie3142** [kaaholst/android-squeezer#678] opened 2021-02-09 23:53 UTC
When first open, I "drill down" through the menu structure to play a track. The choices run as follows:
My Music / Artist / (album) / (track list) / (track)
and then I play the track. Typically the phone goes to sleep and the screen blanks while playing. When the track is finished I want to choose a new track from the same album, but when the screen reawaken, the menu flips back to the top level. You can see it flip back to the top level in an instant. To get to where I was, I have to drill down again. I have to choose My Music / Artist / etc etc all over again! It's a nightmare to use. It should remain where I left it, looking at the track list, not reset to the top level!!

This behaviour also happens if I keep the phone awake but change to another app momentarily. When I return to Squeezer, it jumps back to the top menu every time. 

Please fix this. It cripples usability. I have to use a different player because if this, but I'd rather have Squeezer - if you fix this issue.

My phone: Huawei Honor 20. Latest Android updates.

Thank you.

**Comment by Frankie3142** [comment] 2021-02-10 00:03
Note, the form above removed all the angle brackets I wrote and what I wrote between them, making my message nearly unintelligible. Here's a rewrite using 'soft' brackets...

When first open, I "drill down" through the menu structure to play a track. The choices run as follows:
My Music / Artist / (album) / (track list) / (track) 
and then I play the track. Typically the phone goes to sleep and the screen blanks while playing. When the track is finished I want to choose a new track from the same album, but when the screen reawaken, the menu flips back to the top level. I have to choose My Music / Artist / etc etc all over again! It's a nightmare to use. It should remain where I left it, looking at the track list, not reset to the top level!!

Please fix this. It cripples usability. I have to use a different player because if this, but I'd rather have Squeezer - if you fix this issue.

My phone: Huawei Honor 20. Latest Android updates.

Thank you.

**Comment by kaaholst** [comment] 2021-02-13 15:08
Squeezer is supposed to resume where you left it, when the phone is awaken, at least if you use the latest version from Google Play or F-Droid.

I just tested both of your use cases (phone sleep and switch to another app), and in both cases I was able to return to the same screen and select another track from the same album. Also return to Squeezer via the Recents key or via the Android Home Screen, both gives the expected result.

Perhaps a battery savings option in the phone settings is causing this?

**Comment by Frankie3142** [comment] 2021-02-13 16:29
Hi Kurt

Thank you for your kind reply.

I looked into this issue more closely and found something surprising. It isn't the screen sleep or moving yo other apps that causes it. It happens approximately every 30 seconds, regardless of what the phone is doing! In normal use I hop through the menus very quickly so never noticed this before.

I have made a video to show you the effect. It happens even if I just stay in the Home menu: it blinks and resets itself. Then I tried drilling down a little, and it resets - from anywhere.

The attached video is too big so here is a cloud link. Sorry, replying to this github address is a nightmare.
https://we.tl/t-McXfe2fYp7


I checked battery settings. Auto or manual settings, the behaviour is the same, sadly.

Regards

Frank.

________________________________

**Comment by Lurux** [comment] 2021-03-27 17:31
@kaaholst, I can also observe this on a Samsung tablet (Android 10).

This seems to happen when the application needs to reconnect, which itself seems to happen when the screen blanks for a moment. This may be down to Android power saving indeed.

- _Maybe the app shouldn't go to the toplevel when reconnecting, unless the connection fails ?_

I've also seen the app randomly start reconnecting in loop, like in #680 - which makes the app practically unusable.

- _In the long term, it would be good to fix the random reconnection loops._

**Comment by Frankie3142** [comment] 2021-03-29 16:46
It isn't consistently replicable, but it happens more often than not. I don't have battery save mode on. I tried it and it neither resolves nor worsens the problem. I compared it with another app "Hi-fi Cast" which does the same job as Squeezer (mostly) and that never reverts to it's 'Home Page' during use or after sleep mode, so I don't think it's inevitable that this has to happen.

Should I open a separate thread to highlight Squeezer's outdated support for Scrobbling apps, some of which no longer exist, none of which work, while not recognising those that are present & do, such as 'Pano Scrobbler'?

Cheers

Frankie.

**Comment by kaaholst** [comment] 2021-03-29 22:08
From your description, it seems you are hit by another issue. 

For some reason Android or LMS looses the connection. I haven't been able to find any system in when or why. It may happen of course if there's an issue with the network, but for a few users it disconnects regularly. I am unable to reproduce this myself.

In an attempt to work around this issue I have made a new version of Squeezer which is available in beta. Squeezer attempts a rehandshake when the connection is lost. If that succeeds Squeezer will stay where it is. If that fails it will give up, to avoid an endless loop.

Opt in to receive beta versions of Squeezer by going to https://play.google.com/apps/testing/uk.org.ngo.squeezer and clicking the "Become a tester" button. You can opt out of the beta programme any time.

Please create a separate issue for the scrobbling support.

**Comment by Frankie3142** [comment] 2021-03-29 22:16
Hi! Thank you for that. I have joined the beta program & will report back in a couple of weeks or so. Thank you!

**Comment by kaaholst** [comment] 2021-03-30 06:17
Oh, I see there's already in issue for alternate Scrobblers #655 . Please comment on that issue, instead of creating a new one.

**Comment by kaaholst** [comment] 2021-04-30 21:17
Version 2.2.4 which has just been released, contains a fix to circumvent the disconnection issue, so closing this.

**Closed by kaaholst** 2021-04-30 21:17 UTC
