### ISSUE TITLE
VPN/Wireguard access controlling

### ISSUE THREAD

**Issue by droogi** [kaaholst/android-squeezer#729] opened 2021-10-14 13:18 UTC
Squeezer can only operate when WLAN is available. 
I sometimes use a Wireguard and mobile connection to access my LAN. 
In this case the LMS should also be accessible and the recievers should be controlled.  Is this possible?
Regards, droogi

I appreciate Squeezer very much.

**Comment by droogi** [comment] 2021-10-16 18:18
Thanks for the hint. Wireguard connection to Lms is now possible. 
It does not work on first try, sometimes I have to try ~10 times, but Lms is available via ip:9000 at the same time.
Ok for me to close, but could be optimized ., Thanks
Regards, droogi

**Comment by kaaholst** [comment] 2021-10-21 21:04
For the next version of Squeezer I have removed the Wi-Fi requirement. You can try [this](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing) preview, to see if it works any better.

@droogi I'm not sure what "Lms is available via ip:9000" means. Could you elaborate?

@floot  Thanks for the detailed description. Please try to connect the same address (audio.maison:9000) from a browser on the same device where you are running Squeezer. About logging it's by no means simple. If you feel like it, you can try [Logcat command-line tool](https://developer.android.com/studio/command-line/logcat) which requires that [Android Debug Bridge (adb)](https://developer.android.com/studio/command-line/adb) is installed on your computer.

**Comment by floot** [comment] 2021-10-31 06:11
Here it is! The logcat extract from a failed connection attempt from Squeezer.
Hope this helps!
[logcat.log](https://github.com/kaaholst/android-squeezer/files/7448202/logcat.log)

**Comment by kaaholst** [comment] 2021-11-03 22:12
@floot Thanks for the log. This shows that Squeezer actually connects to LMS "setConnectionState(2 => 4)" but that connection is quickly lost "setConnectionState(4 => 1)". That explains why there are no error messages in the video you sent (like there would have been if the entered address were wrong). It does not, however, explain why the connection is lost.

To investigate this please send the LMS logs of a connection attempt. In the LMS web-interface please select Settings/Advanced/Logging and raise the "(network.cometd) - Cometd protocol logging" log-level to Debug.

**Comment by floot** [comment] 2021-11-10 07:15
Hi!
Thanks @kaaholst for the guidance through the logs!
Here you will find the `server.log` info extracted from one single failed Squeezer connection attempt.
[server.log](https://github.com/kaaholst/android-squeezer/files/7510602/server.log)

**Comment by floot** [comment] 2021-12-01 11:33
Hi!
Do you have enough content to continue your investigation, or do you think about other scenarios?
I could for example test connecting Squeezer to my LMS with the mobile data communication but without Wireshark VPN (with a port temporarily open to the Internet), if you think it is relevant.
Thanks!

**Comment by kaaholst** [comment] 2021-12-02 06:06
@floot Yes please do, that will be good information.
However to solve this issue I think I need to be able to reproduce the issue, currently I cannot do that.
So I'm afraid I need to create setup a similar to what you have, and hope it will fail for me also.
Can you provide assistance with that?

**Comment by floot** [comment] 2021-12-19 08:04
@kaaholst sorry for the delay, I just found some time to test the connection from Squeezer to my LMS with publicly exposed port on the Internet, so I did not use WireGuard this time.
And this time, it succeeded at the first try!
So it likely confirms that the WireGuard VPN connection causes trouble to Squeezer when connecting to LMS.
Attached is the log I got for the direct connection, without WireGuard.

I can prepare details of my WireGuard config so that you can test it for yourself, I just have to get a bit more time to do this.
[server.log](https://github.com/kaaholst/android-squeezer/files/7740470/server.log)

**Comment by floot** [comment] 2021-12-21 18:16
@kaaholst And here are some info about my WireGuard setup.
Actually I installed the WireGuard server on my router running OpenWRT, but the configuration could be adapted to other server OSes.

# Server part

`/etc/config/network`:

```
config wireguard_wg0
        option public_key '[CLIENT_PUBLIC_KEY]'
        option preshared_key '[PRESHARED_KEY]'
        option route_allowed_ips '1'
        list allowed_ips '[CLIENT_IP_IN_THE_VPN_NETWORK]/32'
        option persistent_keepalive '25'
```

# Client (mobile phone) part

I use the official WireGuard app for Android (currently v1.0.20211029 on my phone)

Client configuration of WireGuard has 2 parts:

## Interface

Name: [INTERFACE_NAME]
Private key: [CLIENT_PRIVATE_KEY]
Address: [CLIENT_IP_IN_THE_VPN_NETWORK]/32
DNS Server: [DNS_SERVER_IP]
Listen Port: 51820

## Peer

Public key: [SERVER_PUBLIC_KEY]
Pre-shared Key: [PRESHARED_KEY]
Allowed IP addresses: 0.0.0.0/0
Endpoint: [PUBLIC_IP_OF_THE_VPN_SERVER]:51820


Hope this helps, tell me if you miss something

**Comment by kaaholst** [comment] 2022-03-13 14:56
I managed to get Wireguard working on my setup. I was then able to reproduce this issue when accessing Squeezer from the outside via mobile connection. This in turn enabled me to make a fix.

Please try this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing).

You may continue to use this apk, it will automatically be updated when an new version is released. You can also revert to the version on Google Play, if you prefer to use an official version.

**Comment by droogi** [comment] 2022-03-15 18:18
I tried the march 13th  version and It connects as expected on first try and it's stable.thanks for solving, sorry I could not help with logs.
Regards droogi

**Comment by floot** [comment] 2022-04-17 08:24
Hi! Sorry for the delay... I tested the .apk sent on March 13., and unfortunately I have the very same result as with the mainstream version of the app :-(
I tried with different parameters: squeezebox hostname, ip address, with or without specifying port 9000, but it always behaves the same.
I can help again to debug if needed.
Thanks.

**Comment by kaaholst** [comment] 2022-04-19 16:19
I updated the linked [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing)  and gave it a new version "2.2.10-beta-0" to rule out confusion about which version is running. This version also logs connection errors, so if the problem persists, please attach a new logcat extract.

**Comment by floot** [comment] 2022-05-06 16:05
Hi! Sorry again for the delay, I have a rather slow pace on home computer hacking activities since a few months!
But I am happy to inform you that the version you linked in your latest message solves the problem with WireGuard connections. And in a stable way, as far as I experienced!

Do you have an idea of when the fix is available to a stable version?

Thanks for your the help you already provided until now!

**Comment by kaaholst** [comment] 2022-05-06 17:41
@floot That's good news! thanks for the update.

I have no exact timeline for when this will be released, but it will be in the next version. It is safe for you to keep running 2.2.10-beta-0, it will be automatically updated when the next version is available on Google Play.

Closing this!

**Closed by kaaholst** 2022-05-06 17:41 UTC
